import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Sidebar } from "./stackbuilder/sidebar"
import { cn } from "@/lib/utils"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "MLOps-Webapp",
  description: "Generated by create next app",
}

import React, { Suspense } from 'react';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico?v=2" type="image/x-icon" />
      </head>
      <body className={cn(inter.className, "flex")}>
        {/* Sidebar should take a fixed width */}
        <div className="w-64 fixed h-full">
          <Suspense fallback={<div>Loading...</div>}>
            <Sidebar />
          </Suspense>
        </div>

        {/* Main content */}
        <main className="ml-64 w-full relative overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  )
}
